project_name: aeagle-yttri-lab
run_name: 01_09

max_epochs: 200

fine_tune_lr: False

model:
  d_model: 384
  no_transformer: False
  use_dino: True
  num_heads: 8
  num_layers: 3
  dropout: 0.2
  weight_decay: 1e-3
  drop_path: 0.1
  attn_drop_rate: 0.1
  lr: 1e-5

data:
  train_percent: 0.7
  val_percent: 0.15
  test_percent: 0.15

callbacks:
  early_stopping_patience: 75

data_loading:
  file_name: 01_09
  make_binary: True
  binary_behavior: locomotion

